@echo off
net start "Windows Update"
net start "Windows Search"
net start "Windows Defender"
net start "Superfetch"
net start "Print Spooler"
net start "Windows Firewall"
net start "Windows Backup"
net start "TCP/IP NetBIOS Helper"
net start "Teamviewer 7"
net start "Adobe Flash Player Update Service"
net start "UPnP Device Host"
net start "SSDP Discovery"
net start "Windows Media Player Network Sharing Services"
net start "Themes"
net start "Desktop Windows Manager Session Manager"
net start "Offline Files"
net start "security center"
net start "Error Reporting Service"
net start "Background Intelligent Transfer Service"
net start "PnP-X IP Bus Enumerator"
net start "Application Experience"
net start "Base Filtering Engine"
net start "Diagnostic Policy Service"
net start "Distributed Link Tracking Client"
net start "HomeGroup Provider"
net start "IP Helper"
net start "Machine Debug Manager"
net start "WinHTTP Web Proxy Auto-Discovery Service"
net start "Windows Media Player Network Sharing Service"
net start "System Event Notification Service"
net start "Task Scheduler"
net start "COM+ Event System"
net start "Windows Event Log"
net start "ESL Wire"
