@echo off
@echo "Stoping Services (ignore any errors)"
net stop /Y  "wuauserv"
net stop /Y  "WSearch"
net stop /Y  "WinDefend"
net stop /Y  "SysMain"
net stop /Y  "Spooler"
net stop /Y  "MpsSvc"
net stop /Y  "SDRSVC"
net stop /Y  "lmhosts"
net stop /Y  "upnphost"
net stop /Y  "SSDPSRV"
net stop /Y  "ehRecvr"
net stop /Y  "ehSched"
net stop /Y  "WMPNetworkSvc"
net stop /Y  "Themes"
net stop /Y  "UxSms"
net stop /Y  "CscService"
net stop /Y  "wscsvc"
net stop /Y  "BITS"
net stop /Y  "IPBusEnum"
net stop /Y  "AeLookupSvc"
net stop /Y  "BFE"
net stop /Y  "DPS"
net stop /Y  "TrkWks"
net stop /Y  "HomeGroupProvider"
net stop /Y  "iphlpsvc"
net stop /Y  "MDM"
net stop /Y  "WinHttpAutoProxySvc"
net stop /Y  "SENS"
net stop /Y  "Schedule"
net stop /Y  "EventSystem"
net stop /Y  "c2cpnrsvc"
net stop /Y  "c2cautoupdatesvc"
net stop /Y  "SkypeUpdate"
net stop /Y  "Teamviewer"
net stop /Y  "upnphost"
net stop /Y  "wcncsvc"
net stop /Y  "dnscache"
net stop /Y  "AdobeARMservice"
net stop /Y  "fdphost"
net stop /Y  "fdrespub"
net stop /Y  "ESL Wire Helper Service"
net stop /Y  "Adobe Flash Player Update Service"
net stop /Y  "Error Reporting Service"
net stop /Y  "lanmanserver"
net stop /Y  "lanmanworkstation"
net stop /Y  "lmhosts"
net stop /Y  "aelookupsvc"
net stop /Y  "pcasvc"
net stop /Y  "netman"
