@echo off
@echo "Stoping Services (ignore any errors)"
net stop "wuauserv"
net stop "WSearch"
net stop "WinDefend"
net stop "SysMain"
net stop "Spooler"
net stop "MpsSvc"
net stop "SDRSVC"
net stop "lmhosts"
net stop "upnphost"
net stop "SSDPSRV"
net stop "ehRecvr"
net stop "ehSched"
net stop "WMPNetworkSvc"
net stop "Themes"
net stop "UxSms"
net stop "CscService"
net stop "wscsvc"
net stop "BITS"
net stop "IPBusEnum"
net stop "AeLookupSvc"
net stop "BFE"
net stop "DPS"
net stop "TrkWks"
net stop "HomeGroupProvider"
net stop "iphlpsvc"
net stop "MDM"
net stop "WinHttpAutoProxySvc"
net stop "SENS"
net stop "Schedule"
net stop "EventSystem"
net stop "Windows Event Log"

net stop "ESL Wire Helper Service"
net stop "Skype Update Service"
net stop "Teamviewer 7"
net stop "Adobe Flash Player Update Service"
net stop "Error Reporting Service"
